from __future__ import annotations

from learnloop_sidecar.handlers import (  # noqa: F401
    ai_providers,
    app,
    calibration,
    cli,
    exams,
    facets,
    feedback,
    goals,
    graph,
    ingest,
    inspector,
    knowledge_map,
    library,
    practice,
    proposals,
    provenance,
    queue,
    sessions,
    sqlite_admin,
    teach_back,
    tutor_qa,
)
